services:
  mysql-db:
    container_name: crm-mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  #added here

  backend:
    container_name: crm-backend-container
    build:
      context: ./backend/CRMApplication 
      dockerfile: ../backend.Dockerfile   
    ports:
      - "2025:2020"
    depends_on:
      - mysql-db
    restart: on-failure

  frontend:
    container_name: crm-frontend-container
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    image: hemanth1845/crm-frontend
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  mysql_data: